---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-test

labels:
  - includeSelectors: true
    pairs:
      app: nginx-test

resources:
  - namespace.yaml
  - nginx-deployment.yaml
  - nginx-svc.yaml
  - ingress.yaml

secretGenerator:
- name: tls-cert
  files:
  - tls.crt=certbot/config/live/example.com/fullchain.pem
  - tls.key=certbot/config/live/example.com/privkey.pem
  type: "kubernetes.io/tls"
