defaultRules:
  rules:
    alertmanager: false

alertmanager:
  enabled: false

grafana:
  enabled: true
  defaultDashboardsEnabled: true
  sidecar:
    datasources:
      alertmanager:
        enabled: false

kubeControllerManager:
  enabled: false

coreDns:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

nodeExporter:
  enabled: true
  operatingSystems:
    linux:
      enabled: true
    aix:
      enabled: false
    darwin: # macos
      enabled: false
