# https://taskfile.dev

version: '3'

vars:
  NAMESPACE: argocd
  RELEASE_NAME: argocd
  VERSION: 9.1.7

tasks:
  default:
    cmds:
      - task --list
    silent: true

  help:
    desc: show all available tasks
    cmds:
      - task --list


  #------------------------------
  # ArgoCD tasks
  #------------------------------
  repo:install:
    desc: adds ArgoCD helm repo
    cmds:
      - helm repo add argocd https://argoproj.github.io/argo-helm
      - helm repo update argocd

  repo:list:
    desc: list available ArgoCD releases
    deps: [repo:install]
    cmds:
      - helm search repo argo-cd -l | head -10

  install:
    desc: install ArgoCD
    deps: [repo:install]
    cmds:
      - |
        helm install {{.RELEASE_NAME}} argocd/argo-cd \
          --create-namespace \
          --namespace {{.NAMESPACE}} \
          --version {{.VERSION}}

  argocd:extlb:
    desc: setup external load balancer
    cmds:
      - "kubectl patch svc argocd-server -n argocd -p '{\"spec\": {\"type\": \"LoadBalancer\"}}'"

  argocd:initpw:
    desc: get initial admin secret
    cmds:
      - kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d

  uninstall:
    desc: uninstall ArgoCD
    cmds:
      - helm uninstall {{.RELEASE_NAME}} -n {{.NAMESPACE}} --keep-history

  all:
    desc: full repo setup and ArgoCD install
    cmds:
      - task: install
      - task: argocd:extlb
      - task: argocd:initpw

  clean:
    desc: purge ArgoCD install
    cmds:
      - helm uninstall {{.RELEASE_NAME}} -n {{.NAMESPACE}}
