---
apiVersion: v1
kind: Pod
metadata:
  name: secrets-app
  namespace: app
spec:
  containers:
  - image: google/cloud-sdk:slim
    name: secrets-app
    command: ["sleep","infinity"]
    volumeMounts:
    - name: secretvol
      mountPath: /mnt/secrets
      readOnly: true
  volumes:
  - name: secretvol
    secret:
      secretName: secretkv
      defaultMode: 0400
      items:
      - key: username
        path: username.txt
      - key: password
        path: password.txt
      
