---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-app
  namespace: app
spec:
  vaultAuthRef: static-auth
  type: kv-v2
  mount: secret # mount path
  path: webapp/config # kv secret path
  destination:
    name: secretkv  # k8s secret name
    create: true
  refreshAfter: 30s # static secret refresh interval
