---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "block-nginx-write-index"
  annotations:
    description: "Blocks writes to NGINX html directory"
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: nginx
  kprobes:
  - call: "fd_install"
    syscall: false
    args:
    - index: 0
      type: int
    - index: 1
      type: "file"
    selectors:
    - matchPIDs:
      # this looks at all processes NOT associated with a container's init PID
      # i.e. looks at anything performed inside a "kubectl exec"
      - operator: "NotIn"
        # because nginx will spawn workers to serve the html pages,
        # followForks needs to be set to true here
        followForks: true
        isNamespacePID: true
        values:
        - 1
      matchArgs:
      - index: 1
        operator: "Prefix"
        values:
        - "/usr/share/nginx/html/"
      matchBinaries:
      - operator: "NotIn"
        values:
        - "/usr/bin/more"
      matchActions:
      - action: Sigkill
