---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "log-file-access"
  annotations:
    description: "Log access to files"
spec:
  kprobes:
  - call: "security_file_permission"
    syscall: false
    args:
    - index: 0
      type: "file"
    - index: 1
      type: "int"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Equal"
        values:
        - "/usr/share/nginx/html/50x.html"
        - "/usr/share/nginx/html/index.html"
      matchActions:
      - action: Post
        rateLimit: 1m # rate limit repeated actions by the same thread
