# https://taskfile.dev

version: '3'

vars:
  NAMESPACE: kube-system
  RELEASE_NAME: tetragon
  VERSION: 1.4.1

tasks:
  default:
    cmds:
      - task --list
    silent: true

  help:
    desc: show all available tasks
    cmds:
      - task --list


  #------------------------------
  # Tetragon tasks
  #------------------------------
  repo:install:
    desc: adds Cilium helm repo
    cmds:
      - helm repo add cilium https://helm.cilium.io
      - helm repo update cilium
    internal: true

  repo:list:
    desc: list available Tetragon releases
    deps: [repo:install]
    cmds:
      - helm search repo cilium/tetragon -l | head -10


  install:
    desc: install Tetragon
    deps: [repo:install]
    cmds:
      - |
        helm install {{.RELEASE_NAME}} cilium/tetragon \
          --namespace {{.NAMESPACE}} \
          --version {{.VERSION}}
      - kubectl wait --for=condition=Ready pod -l app.kubernetes.io/component=operator,app.kubernetes.io/instance=tetragon -n {{.NAMESPACE}} --timeout=300s
    status:
      - kubectl wait --for=condition=Ready pod -l app.kubernetes.io/component=operator,app.kubernetes.io/instance=tetragon -n {{.NAMESPACE}} --timeout=300s
    internal: true

  uninstall:
    desc: uninstall Tetragon
    cmds:
      - helm uninstall {{.RELEASE_NAME}} -n {{.NAMESPACE}} --keep-history

  all:
    desc: full repo setup and Tetragon install
    cmds:
      - task: install

  clean:
    desc: purge Tetragon install
    cmds:
      - helm uninstall {{.RELEASE_NAME}} -n {{.NAMESPACE}}
